components/prophet/cluster/cluster_worker.go, components/prophet/cluster/cluster_worker_test.go, components/prophet/prophet_watcher.go, components/prophet/schedule/checker/rule_checker.go, components/prophet/watcher.go, config/config.go, example/cfg.toml, proxy/proxy.go, raftstore/peer_replica.go, raftstore/peer_storage.go, raftstore/store.go, raftstore/store_test.go, raftstore/testutil.go
Fixes #14 
Not Available
Not Available
Not Available
=> Fix #14 add test case for add and remove shard

components/prophet/cluster/cluster.go
**What type of PR1 is this?**
Fixes #18 
Not Available
Not Available
Not Available
=> Fix #18 raftstore proxy missing leader

components/prophet/client.go, components/prophet/client_test.go
Fixes #20 
Not Available
Not Available
Not Available
=> Fix #20 check resource state

components/prophet/join/join.go, raftstore/peer_job.go, raftstore/store_handler.go, raftstore/store_test.go, raftstore/testutil.go, server/server_test.go
Fixes #23 
Not Available
Not Available
Not Available
=> Fix #23 add test helper structs of raftstore

storage/mem/storage.go, storage/pebble/storage.go, storage/storage_data_test.go, storage/storage_meta.go, util/kv_btree.go
Fixes #25 
Not Available
Not Available
Not Available
=> Add prefix scan in storage and test case for it.

config/config.go, raftstore/peer_apply_exec.go
Fixes #27 
Not Available
Not Available
Not Available
=> Fix #27 adjust split custom func definition

config/config.go, raftstore/peer_apply_exec.go, raftstore/peer_event_loop.go, raftstore/peer_job.go, raftstore/snap.go, raftstore/store_handler.go, raftstore/store_test.go
Fixes #29 
Not Available
Not Available
Not Available
=> Custom per group

raftstore/router.go, server/server.go
Fixes #31 
Not Available
Not Available
Not Available
=> Fix #31 export shards in router

Makefile, README.md, components/prophet/config/config.go, components/prophet/pb/gen.sh, config/config.go, example/cfg.toml, grafana/grafana.go, metric/metric_counter.go, metric/metric_gauge.go, metric/metric_histogram.go, metric/push.go, pb/gen.sh, proxy/proxy.go, server/server.go, transport/codec.go
Fixes #33 
Not Available
Not Available
Not Available
=> Fix #33 create shards with multi groups

go.mod, go.sum, vendor/modules.txt
Fixes #37 
Not Available
Not Available
Not Available
=> Fix #37 Update mod version

components/prophet/core/basic_cluster.go
Fixes #41 
Not Available
Not Available
Not Available
=> Fix #41 concurrent map use

components/prophet/election/election_leadship.go, components/prophet/util/etcd.go, config/config.go, raftstore/peer_apply.go, raftstore/peer_apply_exec.go, raftstore/peer_event_loop.go, raftstore/peer_event_post_apply.go, raftstore/peer_event_raft_ready.go, raftstore/peer_job.go, raftstore/peer_replica.go, raftstore/peer_storage.go, raftstore/store.go, raftstore/store_handler.go, raftstore/store_test.go, server/server_test.go, storage/mem/storage.go, storage/pebble/storage.go, storage/storage_base.go, storage/storage_data.go, storage/storage_data_test.go, storage/storage_meta.go
Fixes #46 
Not Available
Not Available
Not Available
=> Decoupling data and metadata storage

raftstore/rpc.go, server/server.go, transport/transport.go
Fixes #53 
Not Available
Not Available
Not Available
=> Fix #53 Too much network log output

components/prophet/storage/storage.go, components/prophet/storage/storage_test.go
Fixes #57 
Not Available
Not Available
Not Available
=> Fix #57 add batch put custom data for pd storage

raftstore/peer_replica.go, raftstore/store_test.go
Fixes #59 
Not Available
Not Available
Not Available
=> Fix #59 speed up leader election of created shard

proxy/proxy.go, raftstore/router.go, server/server.go
Fixes #65 
Not Available
Not Available
Not Available
=> Fix #65 change route API

raftstore/router.go, server/server.go
Fixes #67 
Not Available
Not Available
Not Available
=> change router API

raftstore/prophet_adapter.go
Fixes #69 
Not Available
Not Available
Not Available
=> Fix #69 crash while transfer leader

raftstore/testutil.go, storage/mem/storage.go, storage/pebble/storage.go, storage/storage_data_test.go, storage/storage_meta_test.go
Fixes #73
Not Available
Not Available
Not Available
=> Fix #73 changed MkdirAll's perm to 0755

raftstore/peer_event_loop.go, raftstore/peer_event_proposal.go, raftstore/peer_replica.go, raftstore/store.go, raftstore/store_handler.go, raftstore/store_ready.go
Fixes #76
Not Available
Not Available
Not Available
=> Add the ability to notify peer replica event worker

components/prophet/storage/kv_etcd_test.go, components/prophet/storage/storage.go
Fixes #81 
Not Available
Not Available
Not Available
=> Fix #81  trim prefix not work of LoadRangeByPrefix

components/prophet/client.go, components/prophet/cluster/cluster.go, components/prophet/election/election_leadship.go, components/prophet/member/member.go, components/prophet/prophet.go, components/prophet/prophet_handler.go, components/prophet/prophet_watcher.go, components/prophet/watcher.go, raftstore/prophet_adapter.go, raftstore/router.go, raftstore/store.go, raftstore/store_bootstrap.go, raftstore/store_shards_pool_test.go, raftstore/store_test.go, raftstore/testutil.go, server/server_test.go, server/testutil.go
Fixes #84 
Not Available
Not Available
Not Available
=> Fix #84 lost event notifies after restart

components/prophet/config/config.go, components/prophet/config/persist_options_test.go, server/server_test.go
Fixes #85 
Not Available
Not Available
Not Available
=> Fix #85 config serialization failed

aware/shard.go, components/prophet/config/config.go, components/prophet/config/config_job.go, components/prophet/prophet_job.go, components/prophet/prophet_job_test.go, config/config.go, raftstore/store.go, raftstore/store_shards_pool.go, raftstore/store_shards_pool_test.go, raftstore/store_test.go, raftstore/testutil.go, server/server_test.go, server/testutil.go, storage/storage_base.go, storage/storage_data.go, storage/storage_meta.go
Fixes #94 
Not Available
Not Available
Not Available
=> Fix #94 refactor the code to facilitate testing

command/command.go, pb/pool.go, raftstore/batch.go, raftstore/cmd.go, raftstore/peer_apply.go, raftstore/peer_apply_exec.go, raftstore/peer_event_post_apply.go, raftstore/peer_event_proposal_test.go, raftstore/peer_event_raft_ready.go, raftstore/peer_job.go, raftstore/peer_replica.go, raftstore/store.go, raftstore/testutil.go
Fixes #90 
Not Available
Not Available
Not Available
=> Fix #90 reimplement  ReadIndex logic

raftstore/keys.go, raftstore/peer_apply.go, raftstore/peer_apply_exec.go, raftstore/peer_apply_test.go, raftstore/peer_event_loop.go, raftstore/peer_event_post_apply.go, raftstore/peer_event_proposal_test.go, raftstore/peer_event_raft_ready.go, raftstore/peer_job.go, raftstore/peer_replica.go, raftstore/peer_storage.go, raftstore/store.go, raftstore/store_bootstrap.go, raftstore/store_handler.go, raftstore/store_test.go, raftstore/testutil.go
Fixes #97 
Not Available
Not Available
Not Available
=> Fix #97 crash after restart

raftstore/peer_event_post_apply.go, raftstore/peer_replica.go, raftstore/store.go, raftstore/store_shards_pool.go, raftstore/store_shards_pool_test.go, raftstore/testutil.go
Fixes #98 
Not Available
Not Available
Not Available
=> Fix #98 shard pool not  work on incomplete cluster

config/config.go, raftstore/peer_apply.go, raftstore/peer_apply_exec.go, raftstore/peer_apply_test.go, raftstore/peer_job.go, raftstore/peer_replica.go, raftstore/peer_storage.go, raftstore/store.go, raftstore/testutil.go, storage/mem/storage.go, storage/pebble/storage.go, storage/pebble/storage_test.go, storage/storage_data.go
Fixes #88 
Not Available
Not Available
Not Available
=> Fix #88 sync after admin requests applied

components/prophet/schedule/checker/rule_checker.go
Fixes #103 
Not Available
Not Available
Not Available
=> Fix #103 create shard deadlock

components/prophet/client.go, components/prophet/client_test.go, components/prophet/config/config.go, components/prophet/prophet_handler.go, raftstore/peer_replica.go, raftstore/peer_storage.go, raftstore/store.go, raftstore/store_test.go, raftstore/testutil.go
Fixes #106 
Not Available
Not Available
Not Available
=> Fix #106 prophet rpc timeout

components/prophet/client.go, components/prophet/client_test.go
Fixes #112 
Not Available
Not Available
Not Available
=> Fix #112 prophet client endless loop

.gitignore, storage/pebble/storage_test.go
Fixes #111 
Not Available
Not Available
Not Available
=> Fix #111 remove vendor

raftstore/testutil.go, server/server_test.go, storage/mem/storage.go, storage/pebble/storage.go, vfs/vfs.go
Fixes #118
Not Available
Not Available
Not Available
=> Change the NewStorage interface

storage/pebble/storage_test.go, storage/storage_data_test.go, storage/storage_meta_test.go
Fixes #120 
Not Available
Not Available
Not Available
=> Fix #120 test case compile filed

storage/storage_data_test.go, storage/storage_meta_test.go
Fixes #
Not Available
Not Available
Not Available
=> New storage api fix

storage/storage_base.go, storage/storage_data_test.go, storage/storage_meta_test.go
Fixes #
Not Available
Not Available
Not Available
=> close storage instances in tests

storage/storage_data_test.go, storage/storage_meta_test.go
Fixes #
Not Available
Not Available
Not Available
=> vfs test fix

Makefile, doc.go
Fixes #
Not Available
Not Available
Not Available
=> add the race-test target to the Makefile

components/prophet/schedule/filter/filters.go, raftstore/peer_event_raft_ready.go, raftstore/peer_replica.go, raftstore/store.go, raftstore/store_test.go, raftstore/testutil.go
Fixes #123 
Not Available
Not Available
Not Available
=> Fix #123  log committed before register delegate

raftstore/peer_apply_test.go, raftstore/peer_event_proposal_test.go, raftstore/store_shards_pool_test.go, raftstore/store_test.go, server/server_test.go, storage/storage_data_test.go, storage/storage_meta_test.go, util/leaktest/leak.go
Fixes #130
Not Available
Not Available
Not Available
=> Add #130 goroutine leaktest

raftstore/snap.go, raftstore/store.go, snapshot/snaphot_manager.go
Fixes #132 
Not Available
Not Available
Not Available
=> Fix goroutine leak in snapshot manager

util/leaktest/leak.go
Fixes #
Not Available
Not Available
Not Available
=> Disable goroutine leak test

raftstore/testutil.go
Fixes #138
Not Available
Not Available
Not Available
=> Fix incorrect data directory path

config/config.go, raftstore/peer_event_raft_ready.go, raftstore/peer_event_raft_ready_test.go, raftstore/peer_job.go, raftstore/store.go, raftstore/store_test.go, raftstore/testutil.go
Fixes #133 
Not Available
Not Available
Not Available
=> Fix #133 crash when advance raft

config/config.go, raftstore/peer_event_raft_ready.go, raftstore/peer_event_raft_ready_test.go, raftstore/peer_storage.go, raftstore/testutil.go
Fixes #133 
Not Available
Not Available
Not Available
=> Fix #133 case 2 set snapshot job is too slow

raftstore/peer_apply_test.go, raftstore/store_test.go, storage/mem/storage.go, storage/storage_meta_test.go
Fixes #145 
Not Available
Not Available
Not Available
=> Fix #145 fix unstable test

.github/workflows/build_cube.yml
Fixes #151 
If build fails, the step to show system info will be canceled. Function always() can guarantee the step to be done.
Not Available
Not Available
=> [#151] Always show system info on work-flow even build fails

.github/workflows/build_cube.yml
Fixes #154 
Not Available
Not Available
Not Available
=> [#154] Update the mac os version to 11

.github/workflows/build_cube.yml
Fixes #156 
Not Available
Not Available
Not Available
=> [#156] Show hardware info on mac os

raftstore/snap.go
Fixes #158 
Replaced os.RemoveAll with vfs.FS.RemoveAll
Not Available
Not Available
=> Replaced os.RemoveAll with FS.RemoveAll

raftstore/peer_event_loop.go, raftstore/store.go
Fixes #160 
Not Available
Not Available
Not Available
=> Fix cached term is likely to be off by one

raftstore/peer_apply_test.go, raftstore/peer_event_proposal_test.go, raftstore/peer_event_raft_ready_test.go, raftstore/store_shards_pool_test.go, raftstore/store_test.go, raftstore/testutil.go
Fixes #101 
Not Available
Not Available
Not Available
=> Fix #101 adjust ticker according to fsync time

.github/ISSUE_TEMPLATE/10_bug_report.md
Fixes #
Not Available
Not Available
Not Available
=> Add issue template

config/config.go, raftstore/keys.go, raftstore/peer_storage.go, raftstore/store.go, raftstore/store_bootstrap.go, raftstore/store_route_handler.go, raftstore/store_test.go
Fixes #166 
Not Available
Not Available
Not Available
=> Fix #166 wrong timing to write dynamic shard state

raftstore/peer_event_loop.go, raftstore/peer_event_proposal.go, raftstore/peer_replica.go, raftstore/store.go, raftstore/store_handler.go
Fixes #168 
Not Available
Not Available
Not Available
=> Fix #168 missing work ready notify

config/config.go, raftstore/store.go, raftstore/store_shards_pool.go, raftstore/store_shards_pool_test.go, raftstore/testutil.go
- [] API-change
Fixes #153 
Not Available
Not Available
Not Available
=> Fix #153 Add shard factory used by shard pool

raftstore/peer_event_raft_ready.go
Fixes #175
Not Available
Not Available
Not Available
=> Changed how the parallel fsync optimization is implemented

components/prophet/join/join.go
Fixes #187 
Not Available
Not Available
Not Available
=> Fix #187 retry instead of panic when join cluster

storage/pebble/event.go, storage/pebble/storage.go
Fixes #189 
Not Available
Not Available
Not Available
=> Add an event listener for pebble

components/prophet/config/config.go, config/config.go, raftstore/store_shards_pool.go, raftstore/store_shards_pool_test.go
Fixes #192 
Not Available
Not Available
Not Available
=> Fix  #192 shard pool deadlock

raftstore/peer_event_raft_ready.go, raftstore/store_handler.go
Fixes #
Not Available
Not Available
Not Available
=> Fix #206 do apply committed log fatal

raftstore/peer_replica.go, test.sh
Fixes #209 
Not Available
Not Available
Not Available
=> Fix #209 panic: index out of range

CHANGELOG.md, README.md
Fixes #
Not Available
Not Available
Not Available
=> Adjust doc

components/prophet/cluster/cluster.go, components/prophet/cluster/cluster_worker.go, components/prophet/core/basic_cluster.go, raftstore/store_shards_pool.go, raftstore/store_shards_pool_test.go
Fixes #212 
Not Available
Not Available
Not Available
=> Fix #212 remove panic, make wait and push atomic

components/prophet/option.go, components/prophet/prophet_transport.go, go.mod, go.sum, raftstore/rpc.go, server/server.go, transport/transport.go
Fixes #214 
Not Available
Not Available
Not Available
=> Fix #214 upgrade goetty

.gitignore
Fixes #
To avoid adding redundant files to the repo. 
Not Available
Not Available
=> Add *.swp, *.txt, *.log to .gitignore

README.md, licenses/Apache2.txt, licenses/README.md
Fixes #
Not Available
Not Available
Not Available
=> License update

go.mod, go.sum, util/leaktest/leak.go
Fixes #
Not Available
Not Available
Not Available
=> added a wrapper for the leaktest util

components/prophet/cluster/cluster.go, raftstore/router.go
Fixes #
Not Available
Not Available
Not Available
=> Add more log to debug

Makefile, components/prophet/client.go, components/prophet/join/join.go, components/prophet/prophet_leader.go, components/prophet/prophet_watcher.go, components/prophet/storage/storage.go, components/prophet/util/keyutil/util.go, go.mod, go.sum, raftstore/peer_apply.go, raftstore/peer_apply_exec.go, raftstore/peer_apply_test.go, raftstore/peer_event_post_apply.go, raftstore/peer_event_proposal.go, raftstore/peer_replica.go, raftstore/prophet_adapter.go, raftstore/router.go, raftstore/snap.go, raftstore/store.go, raftstore/testutil.go, test.sh, transport/transport.go, util/testutil/ports.go
Fixes #238 
Not Available
Not Available
Not Available
=> Fix #238 timeout to execute read/write operations

raftstore/execute_context.go, raftstore/execute_context_test.go, raftstore/replica.go, raftstore/replica_event_loop.go, raftstore/replica_event_read_index.go, raftstore/replica_state_machine_exec.go, storage/executor/simple/kv_executor.go, storage/kv/kv_data_storage.go, storage/kv/kv_data_storage_test.go, storage/storage_data.go
Fixes #257 
Not Available
Not Available
Not Available
=> Fix #257 refactored storage.Context

components/log/fields.go, pb/errorpb/errorpb.pb.go, pb/gen.sh, pb/meta/meta.pb.go, pb/rpc/rpc.pb.go, pb/rpc/rpc.proto, raftstore/execute_context.go, raftstore/execute_context_test.go, raftstore/proposal_batch.go, raftstore/proposal_batch_test.go, raftstore/replica.go, raftstore/replica_event_loop.go, raftstore/replica_event_proposal.go, raftstore/replica_event_raft_ready.go, raftstore/replica_event_read_index.go, raftstore/testutil.go
Fixes #259 
Not Available
Not Available
Not Available
=> Fix #259 renamed a few types incorrectly named

raftstore/execute_context.go, raftstore/execute_context_test.go, raftstore/proposal_batch.go, raftstore/replica_state_machine.go, raftstore/replica_state_machine_exec.go
Fixes #261 
Not Available
Not Available
Not Available
=> Fix #261 refactored applyContext used in state machines

.gitignore, logdb/logdb_test.go, raftstore/execute_context_test.go, raftstore/replica_destroy_test.go, raftstore/replica_event_loop_test.go, raftstore/replica_event_raft_ready_test.go, raftstore/replica_state_machine_test.go, raftstore/snapshotter_test.go, snapshot/snapshot_env_test.go, util/leaktest/leak.go
Fixes #333 
Not Available
Not Available
Not Available
=> Resolve #333 added leaked file descriptor and goroutine checks to some tests

Makefile, util/leaktest/leak.go
Fixes #351 
Not Available
Not Available
Not Available
=> Resolve #351 goroutine leak check disabled by default

logdb/logdb.go, logdb/logdb_test.go, raftstore/snapshotter.go
Fixes #356 
Not Available
Not Available
Not Available
=> Resolve #356 removed SaveSnapshot() from logdb.LogDB

Makefile, components/prophet/cluster/cluster_worker.go, components/prophet/config/config.go, components/prophet/join/join.go, components/prophet/pb/metapb/metapb.pb.go, components/prophet/pb/metapb/metapb.proto, components/prophet/pb/rpcpb/rpcpb.pb.go, components/prophet/prophet.go, go.mod, go.sum, raftstore/integration_split_test.go, raftstore/proxy.go, raftstore/proxy_backend.go, raftstore/proxy_rpc.go, raftstore/store_bootstrap.go, raftstore/worker_pool.go, raftstore/worker_pool_test.go, test/basic_test.go
Fixes #353 
Not Available
Not Available
Not Available
=> Fix goroutine leaks in raftstore tests

raftstore/replica.go, raftstore/replica_event_loop.go, raftstore/replica_event_proposal.go, raftstore/replica_event_raft_ready.go
Fixes #369 
Not Available
Not Available
Not Available
=> Resolve #369 remove redundant object copies when processing raft.Ready

raftstore/replica_event_loop.go, raftstore/replica_event_proposal.go
Fixes #366 
Not Available
Not Available
Not Available
=> Fix #366 fixed replica.handleEvent() to return false as expected

raftstore/replica_create.go, raftstore/replica_create_test.go, raftstore/testutil.go
Fixes #383 
Not Available
Not Available
Not Available
=> Fix save metadata with invalid replica id

raftstore/store.go, raftstore/store_route_handler.go, raftstore/store_route_handler_test.go
Fixes #381 
Not Available
Not Available
Not Available
=> Fix skip create replica if not found record

raftstore/log_reader.go, raftstore/log_reader_test.go, raftstore/replica_event_raft_ready.go, raftstore/replica_snapshot.go
Fixes #358 
Not Available
Not Available
Not Available
=> Resolve #358 create snapshot when requested

logdb/logdb.go, raftstore/replica_event_raft_ready.go, raftstore/replica_event_raft_ready_test.go
Fixes #386 
Not Available
Not Available
Not Available
=> Save RaftReady in any case

raftstore/replica_event_loop.go, raftstore/replica_event_loop_test.go, raftstore/replica_event_raft_ready.go, raftstore/replica_event_raft_ready_test.go, raftstore/worker_pool.go, raftstore/worker_pool_test.go
Fixes #390 
Not Available
Not Available
Not Available
=> Resolve #390 refactor how raft ready is processed

Makefile
also fixed a minor issue that prevented from running race tests
Fixes #394 
Not Available
Not Available
Not Available
=> Resolve #394 added a all-tests Makefile target

raftstore/replica.go, raftstore/replica_event_loop.go
Fixes #392 
Not Available
Not Available
Not Available
=> Fix too many logs when stop replica

raftstore/store_bootstrap.go
Fixes #397 
Not Available
Not Available
Not Available
=> Only prophet leader bootstrap cluster

raftstore/testutil.go
Fixes #399 
Not Available
Not Available
Not Available
=> Adjusting the test cluster start-up sequence

storage/kv/keys.go, storage/kv/keys_test.go
Fixes #404 
Not Available
Not Available
Not Available
=> Add decode data key

raftstore/replica.go
Fixes #402 
Not Available
Not Available
Not Available
=> Fix shard created event notify

components/prophet/client.go, components/prophet/cluster/cluster.go, components/prophet/prophet.go, components/prophet/prophet_handler.go, components/prophet/prophet_leader.go, components/prophet/prophet_watcher.go, go.mod, go.sum
Fixes #
Not Available
Not Available
Not Available
=> Fix some data race

raftstore/replica_event_loop.go
Fixes #417 
Not Available
Not Available
Not Available
=> Fix #417 high cpu load caused by bad merge

raftstore/replica_event_loop.go, raftstore/replica_event_loop_test.go, raftstore/replica_event_proposal.go
Fixes #417 
Not Available
Not Available
Not Available
=> Fix bad merge

raftstore/replica_destroy.go, raftstore/replica_destroy_test.go
Fixes #420 
Not Available
Not Available
Not Available
=> Fix #420 handle vacuuming the replica multiple times

raftstore/replica_state_machine.go, raftstore/replica_state_machine_test.go
Fixes #422 
Not Available
Not Available
Not Available
=> allow entries to be skipped after split

components/prophet/client.go, components/prophet/watcher.go
Fixes #431 
Not Available
Not Available
Not Available
=> Fix data race

raftstore/batch.go, raftstore/batch_test.go
Fixes #430 
Not Available
Not Available
Not Available
=> Fix response bug

Makefile
Fixes #
Not Available
Not Available
Not Available
=> Update the static check target in Makefile

raftstore/integration_split_test.go, raftstore/store_test.go, raftstore/testutil.go
Fixes #438 
Not Available
Not Available
Not Available
=> Fix test timeout

raftstore/replica_event_loop.go, raftstore/worker_pool.go
Fixes #
Not Available
Not Available
Not Available
=> Added some worker pool related logging

raftstore/integration_split_test.go, raftstore/proxy.go, raftstore/replica_event_raft_ready.go, raftstore/router.go, raftstore/store.go, raftstore/store_handler.go, raftstore/testutil.go
Fixes #
Not Available
Not Available
Not Available
=> Fix some testcase failed

raftstore/replica.go, raftstore/replica_event_loop.go, raftstore/store.go, raftstore/store_debug.go
Fixes #446 
Not Available
Not Available
Not Available
=> add debug info

raftstore/replica_event_loop.go, raftstore/worker_pool.go
Fixes #
Not Available
Not Available
Not Available
=> Added more logging for the worker pool

raftstore/integration_split_test.go, raftstore/testutil.go
Fixes #457 
Not Available
Not Available
Not Available
=> Wait replica change to voter

components/prophet/pb/metapb/metapb.pb.go, components/prophet/pb/rpcpb/rpcpb.pb.go, config/config.go, pb/errorpb/errorpb.pb.go, pb/meta/meta.pb.go, pb/rpc/rpc.pb.go, pb/rpc/rpc.proto, raftstore/prophet_adapter.go, raftstore/prophet_adapter_test.go, raftstore/replica.go, raftstore/replica_event_loop.go, raftstore/replica_event_loop_test.go, raftstore/replica_state_machine.go, raftstore/replica_state_machine_exec.go, raftstore/replica_state_machine_exec_test.go, raftstore/store.go, raftstore/store_handler.go, raftstore/store_handler_test.go, raftstore/store_timer_task.go, raftstore/store_timer_task_test.go
Fixes #320 
Not Available
Not Available
Not Available
=> Reimplement raft log compact

raftstore/store.go
Fixes #456 
Not Available
Not Available
Not Available
=> retry if allocate id failed

logdb/logdb.go, logdb/logdb_test.go, raftstore/replica.go, raftstore/replica_event_loop.go, raftstore/replica_event_loop_test.go, raftstore/replica_event_raft_ready.go, raftstore/replica_event_raft_ready_test.go, raftstore/replica_snapshot.go, raftstore/replica_snapshot_test.go, raftstore/snapshotter.go, raftstore/store.go, transport/job.go, transport/snapshot.go, transport/transport.go
Fixes #322 
Not Available
Not Available
Not Available
=> Added support for applying snapshot

components/prophet/election/election_leaser.go, raftstore/integration_split_test.go, raftstore/store.go
Fixes #440 
Not Available
Not Available
Not Available
=> Fix testcase of split

components/prophet/cluster/coordinator.go
Fixes #465 
Not Available
Not Available
Not Available
=> Fix missing patrol replicas with multi-groups

raftstore/integration_split_test.go
Fixes #466 
Not Available
Not Available
Not Available
=> fix deadlock between tests and handle heartbeat

aware/shard.go, raftstore/replica_apply_result.go, raftstore/testutil.go
Fixes #457 
Not Available
Not Available
Not Available
=> Add shard updated in aware after conf change

raftstore/replica_event_raft_ready.go, raftstore/replica_event_raft_ready_test.go, raftstore/store.go, raftstore/testutil.go, transport/snapshot_test.go, transport/transport.go
Fixes #
Not Available
Not Available
Not Available
=> Send snapshot when requested

components/prophet/pb/metapb/metapb.pb.go, components/prophet/pb/rpcpb/rpcpb.pb.go, pb/errorpb/errorpb.pb.go, pb/gen.sh, pb/meta/meta.pb.go, pb/meta/meta.proto, pb/rpc/rpc.pb.go, raftstore/execute_context.go, raftstore/execute_context_test.go, raftstore/replica_create.go, raftstore/replica_create_test.go, raftstore/replica_snapshot.go, raftstore/replica_snapshot_test.go, raftstore/replica_state_machine_exec.go, raftstore/snapshotter.go, storage/kv/kv_base_storage.go, storage/kv/kv_base_storage_test.go, storage/kv/kv_data_storage.go, storage/storage_data.go
Fixes #471 
Not Available
Not Available
Not Available
=> Removed term from the storage.DataStorage interface

raftstore/worker_pool.go
Fixes #
Not Available
Not Available
Not Available
=> Removed some  worker pool logging

components/prophet/pb/metapb/metapb.pb.go, components/prophet/pb/rpcpb/rpcpb.pb.go, pb/errorpb/errorpb.pb.go, pb/meta/meta.pb.go, pb/meta/meta.proto, pb/rpc/rpc.pb.go, raftstore/integration_snapshot_test.go, raftstore/replica_event_raft_ready.go, raftstore/replica_event_raft_ready_test.go, raftstore/replica_snapshot.go, raftstore/replica_state_machine.go, raftstore/snapshotter.go, raftstore/testutil.go, transport/chunk.go, transport/chunk_test.go, transport/snapshot.go, transport/transport.go
Fixes #481 
Not Available
Not Available
Not Available
=> Fix end-to-end replication via snapshot

raftstore/replica_state_machine_exec.go, raftstore/replica_state_machine_exec_test.go
Fixes #483 
Not Available
Not Available
Not Available
=> Take persistent log index into consideration when compacting logs

raftstore/testutil.go
Fixes #485 
Not Available
Not Available
Not Available
=> Support start and stop single node

raftstore/integration_snapshot_test.go
Fixes #
Not Available
Not Available
Not Available
=> Fix forTestCompactionAndSnapshot

raftstore/replica.go, raftstore/replica_event_raft_ready.go, raftstore/replica_event_raft_ready_test.go
Fixes #488 
Not Available
Not Available
Not Available
=> Fix #488 limit what committed raft log entries to apply

raftstore/replica.go, raftstore/replica_event_loop.go
Fixes #490 
Not Available
Not Available
Not Available
=> Fix #490 feed ConfState from the latest snapshot to raft node

raftstore/replica_event_loop.go, raftstore/replica_snapshot.go, raftstore/replica_state_machine_exec.go, raftstore/snapshotter.go
Fixes #
Not Available
Not Available
Not Available
=> Added more debug logging

raftstore/replica_event_loop.go
Fixes #
Not Available
Not Available
Not Available
=> Set pushedIndex after applying initial snapshot

components/prophet/cluster/coordinator.go
Fixes #
Not Available
Not Available
Not Available
=> Remove debug information

raftstore/testutil.go
Fixes #
Not Available
Not Available
Not Available
=> Add status for test framework

Makefile, raftstore/store_extension.go, raftstore/store_test.go
Fixes #497 
Not Available
Not Available
Not Available
=> Added a matrixone_test build tag

raftstore/store.go, transport/transport.go, transport/transport_test.go
Fixes #499 
Not Available
Not Available
Not Available
=> Fix ContainerResolver panic

raftstore/replica_state_machine_exec.go, raftstore/replica_state_machine_exec_test.go
Fixes #506 
Not Available
Not Available
Not Available
=> Fix panic on remove non-existent replica

storage/kv/kv_data_storage.go, storage/kv/kv_data_storage_test.go
Fixes #504 
Not Available
Not Available
Not Available
=> Fix forget to remove persistentAppliedIndexes

logdb/logdb.go, logdb/logdb_test.go, raftstore/replica_event_loop_test.go, raftstore/replica_event_raft_ready_test.go, raftstore/replica_snapshot.go, raftstore/replica_snapshot_test.go, snapshot/snapshot_env.go
Fixes #502 
Not Available
Not Available
Not Available
=> Fix snapshot image compaction

components/prophet/cluster/cluster.go
Fixes #508 
Not Available
Not Available
Not Available
=> Fix deadlock when calling GetScheduleGroupKeys

components/prophet/cluster/cluster.go, raftstore/integration_snapshot_test.go, raftstore/integration_split_test.go, raftstore/testutil.go
Fixes 
Not Available
Not Available
Not Available
=> Fix test wait change voter assert

.gitignore, Dockerfile-test, logdb/logdb_test.go, raftstore/snapshotter_test.go, storage/kv/kv_data_storage_test.go, test.sh, transport/snapshot_test.go
Fixes #512 
Not Available
Not Available
Not Available
=> Support run testcase in docker

logdb/logdb.go, logdb/logdb_test.go, raftstore/replica.go, raftstore/replica_create_test.go, raftstore/replica_event_loop_test.go, raftstore/replica_event_proposal.go, raftstore/replica_event_raft_ready_test.go, raftstore/replica_snapshot.go, raftstore/replica_snapshot_test.go, raftstore/replica_state_machine_exec_test.go, raftstore/replica_test.go
Fixes #514 
Not Available
Not Available
Not Available
=> Fix LogReader initialization in the presence of snapshotting

logdb/logdb_test.go
Fixes #
Not Available
Not Available
Not Available
=> Added a LogDB test

raftstore/replica_event_raft_ready.go, raftstore/replica_event_raft_ready_test.go, raftstore/replica_snapshot_test.go, raftstore/snapshotter.go, raftstore/snapshotter_test.go, snapshot/snapshot_env.go, snapshot/snapshot_env_test.go, transport/chunk.go, util/fileutil/utils.go
Fixes #
Not Available
Not Available
Not Available
=> Simplified how orphan snapshots are handled

raftstore/integration_split_test.go, raftstore/prophet_adapter_test.go, raftstore/testutil.go
Fixes #
Not Available
Not Available
Not Available
=> remove test transport

raftstore/integration_split_test.go, raftstore/replica_snapshot.go, raftstore/replica_snapshot_test.go
Fixes #518 
Not Available
Not Available
Not Available
=> Notify aware after  snapshot applied

raftstore/replica_snapshot_test.go, storage/kv/kv_data_storage.go
Fixes #521 
Not Available
Not Available
Not Available
=> Fixed kvDataStorage to update persistentLogIndex after applying snapshot

Dockerfile-test, test.sh, test_loop.sh
Fixes #
Not Available
Not Available
Not Available
=> speedup test in docker

storage/kv/pebble/storage.go
Fixes #526 
Not Available
Not Available
Not Available
=> Explicitly set pebble's max opened file to 1024

raftstore/replica_apply_result.go, raftstore/replica_apply_result_test.go
Fixes #530 
Not Available
Not Available
Not Available
=> Fix statistics are overwritten by empty raft log

raftstore/store_extension_test.go, raftstore/store_test.go
Fixes #
Not Available
Not Available
Not Available
=> move TestLogDBGetter to tag-constrainted test file

raftstore/replica_snapshot.go, raftstore/replica_snapshot_test.go
Fixes #534 
Not Available
Not Available
Not Available
=> Update key ranges after snapshot applied

raftstore/store_handler.go, raftstore/store_handler_test.go
Fixes #535 
Not Available
Not Available
Not Available
=> Fix wrong overlap check implementation

raftstore/replica_snapshot_test.go
Fixes #
Not Available
Not Available
Not Available
=> Fix bad merge in test TestReplicaSnapshotCanBeApplied

raftstore/replica_create.go, raftstore/replica_create_test.go, raftstore/replica_snapshot_test.go, raftstore/replica_state_machine_exec.go
Fixes #541 
Not Available
Not Available
Not Available
=> Fix missing new shards metadata to datastorage

raftstore/replica_apply_result.go, raftstore/replica_apply_result_test.go, raftstore/replica_state_machine.go, raftstore/replica_state_machine_exec.go
Fixes #
Not Available
Not Available
Not Available
=> Allow apply result metrics to be ignored

raftstore/integration_basic_test.go, raftstore/proxy.go, raftstore/replica_apply_result.go, raftstore/store.go, raftstore/testutil.go, server/server.go, server/server_test.go
Fixes #
Not Available
Not Available
Not Available
=> Shortcut method for add shard label

raftstore/replica_create.go, raftstore/replica_create_test.go, raftstore/replica_state_machine_exec.go
Fixes #547 
Not Available
Not Available
Not Available
=> Fix always save init raft log

logdb/logdb.go, raftstore/log_reader.go, raftstore/replica.go, raftstore/replica_apply_result.go
Fixes #
Not Available
Not Available
Not Available
=> Minor fix for logging

raftstore/replica_state_machine.go, raftstore/replica_state_machine_test.go
Fixes #550 
Not Available
Not Available
Not Available
=> Fix apply log in destroying state

raftstore/split_checker.go, raftstore/split_checker_test.go
Fixes #551 
Not Available
Not Available
Not Available
=> Fix perform split checker in destroying state

raftstore/store_bootstrap.go
Fixes #554 
Not Available
Not Available
Not Available
=> Fix store not register to prophet after restart

raftstore/replica_event_loop.go, raftstore/replica_event_loop_test.go
Fixes #556 
Not Available
Not Available
Not Available
=> Never remove the latest snapshot record from LogDB

components/prophet/cluster/cluster.go, components/prophet/cluster/coordinator.go, components/prophet/core/basic_cluster.go, components/prophet/core/resource.go, components/prophet/schedule/checker/rule_checker.go
Fixes #560 
Not Available
Not Available
Not Available
=> Add schdule for destroying resources

raftstore/store_bootstrap.go
Fixes #558 
Not Available
Not Available
Not Available
=> Fix action after store bootstrapped

components/prophet/prophet_leader.go
Fixes #559 
Not Available
Not Available
Not Available
=> Assign logger to prophet client

components/log/fields.go, raftstore/read_index_queue.go, raftstore/replica.go, raftstore/replica_apply_result.go, raftstore/replica_event_loop.go, raftstore/replica_event_raft_ready.go, raftstore/replica_snapshot.go, raftstore/replica_state_machine.go, raftstore/replica_state_machine_exec.go, raftstore/snapshotter.go
Fixes #
Not Available
Not Available
Not Available
=> Some cleanups for zap logging fields

config/config.go, raftstore/integration_split_test.go, raftstore/replica.go, raftstore/replica_destory_task.go, raftstore/replica_destory_task_test.go, raftstore/replica_event_raft_ready.go, raftstore/replica_state_machine_exec.go, raftstore/split_checker.go, raftstore/store.go, raftstore/store_timer_task.go, raftstore/testutil.go
Fixes #533 
Not Available
Not Available
Not Available
=> Fix start replica destroy task after replica state check

logdb/logdb.go, logdb/logdb_test.go, raftstore/replica_apply_result.go
Fixes #
This PR adds LogDB safety checks. It helps to prevent invalid remove operations that can potentially corrupt the LogDB state. It can prevent issues like #556. 
Not Available
Not Available
=> Add LogDB safety checks

raftstore/replica.go, raftstore/replica_event_loop.go, raftstore/replica_event_loop_test.go, raftstore/replica_event_raft_ready_test.go, raftstore/replica_snapshot.go, raftstore/replica_snapshot_test.go, raftstore/replica_test.go
Fixes #568 
Not Available
Not Available
Not Available
=> Fixed snapshot compaction to remove snapshot images whenever possible

raftstore/replica_event_loop.go, raftstore/replica_event_loop_test.go
Fixes #570 
Not Available
Not Available
Not Available
=> Fix force compaction not work

raftstore/replica_apply_result.go, raftstore/replica_event_loop.go, raftstore/replica_event_loop_test.go, raftstore/replica_event_raft_ready_test.go, raftstore/replica_snapshot.go, raftstore/replica_snapshot_test.go, raftstore/replica_state_machine_exec_test.go
Fixes #
Not Available
Not Available
Not Available
=> Implement log and snapshot compaction as event worker actionns

components/prophet/config/config.go, components/prophet/config/default.go, components/prophet/join/join.go, components/prophet/prophet.go, config/config.go, raftstore/store.go, raftstore/store_bootstrap.go, raftstore/store_test.go, raftstore/testutil.go
Fixes #573 
Not Available
Not Available
Not Available
=> Support advertise rpc addresses

components/prophet/client.go, components/prophet/option.go, components/prophet/prophet.go, components/prophet/prophet_transport.go, components/prophet/watcher.go
Fixes #
Not Available
Not Available
Not Available
=> Add more stop prophet log

raftstore/integration_split_test.go
Fixes #576 
Not Available
Not Available
Not Available
=> Fix testcase assert

components/prophet/client.go, components/prophet/watcher.go
Fixes #
Not Available
Not Available
Not Available
=> Fix deadlock in prophet client

raftstore/store.go, transport/transport.go, transport/transport_test.go
Fixes #579 
Not Available
Not Available
Not Available
=> Fix nil filter added to transport

raftstore/integration_basic_test.go, raftstore/prophet_adapter_test.go, raftstore/proposal_batch_test.go, raftstore/proxy_backend_test.go, raftstore/proxy_rpc_test.go, raftstore/proxy_test.go, raftstore/replica_apply_result_test.go, raftstore/replica_destory_task_test.go, raftstore/replica_destroy_test.go, raftstore/replica_event_loop_test.go, raftstore/router_test.go, raftstore/split_checker_test.go, raftstore/store_bootstrap_test.go, raftstore/store_handler_test.go, raftstore/store_route_handler_test.go, raftstore/store_shards_pool_test.go, raftstore/store_test.go, raftstore/store_timer_task_test.go, raftstore/testutil.go
Fixes #
Not Available
Not Available
Not Available
=> Fixed some goroutine leaks in tests

logdb/logdb.go, logdb/logdb_test.go, raftstore/replica_destroy.go, raftstore/store_test.go, storage/kv/pebble/storage.go, util/write_batch.go
Fixes #585 
Not Available
Not Available
Not Available
=> [WIP] Delete LogDB records when replica is destroyed

raftstore/store.go
Fixes #587 
Not Available
Not Available
Not Available
=> Shutdown replicas when store.Stop() is called

raftstore/issue_test.go
Fixes #
Not Available
Not Available
Not Available
=> Fixed a goroutine leak in test

storage/kv/kv_base_storage.go
Fixes #591 
Not Available
Not Available
Not Available
=> Fixed kv base storage to atomically apply snapshot

raftstore/replica_destroy.go, storage/storage_data.go
Fixes #594 
Not Available
Not Available
Not Available
=> Allow engine to reject SaveShardMetadata after split

raftstore/router.go, raftstore/store.go
Fixes #597 
Not Available
Not Available
Not Available
=> Fixed a race condition on how replicas are created & stopped

components/prophet/client.go, raftstore/replica.go, raftstore/store_timer_task.go
Fixes #584 
Not Available
Not Available
Not Available
=> Fix log level

components/prophet/client.go, raftstore/replica.go, raftstore/store_timer_task.go
Fixes #599 
Not Available
Not Available
Not Available
=> Fix can not close prophet client

raftstore/replica_event_loop.go
Fixes #82 
Not Available
Not Available
Not Available
=> Better error handling

raftstore/replica_event_loop.go, raftstore/replica_event_loop_test.go, raftstore/replica_snapshot.go
Fixes #606 
Not Available
Not Available
Not Available
=> Fixed how initial snapshot is applied

raftstore/replica.go, raftstore/replica_apply_result.go, raftstore/replica_create.go, raftstore/replica_create_test.go, raftstore/store.go, raftstore/store_handler.go, raftstore/store_route_handler.go
Fixes #609 
Not Available
Not Available
Not Available
=> speed up leader election at bootstrap

logdb/logdb.go, raftstore/replica_event_raft_ready.go
Fixes #
Not Available
Not Available
Not Available
=> Made LogDB less verbose in logging

components/prophet/core/container.go
Fixes #575 
Not Available
Not Available
Not Available
=> Fix data race with container label

components/prophet/core/container.go, components/prophet/core/container_stats.go, components/prophet/schedulers/utils.go
Fixes #613 
Not Available
Not Available
Not Available
=> Use resource count as score when high disk space

components/prophet/core/container.go
Fixes #428 
Not Available
Not Available
Not Available
=> Fix update the loop variable label  not affect

components/prophet/schedule/checker/rule_checker.go
Fixes #429 
Not Available
Not Available
Not Available
=> Fix the role field in replcia is not assigned

raftstore/replica_destroy.go
Fixes #618 
Not Available
Not Available
Not Available
=> Fix destroy replica tests

raftstore/testutil.go
Fixes #620 
Not Available
Not Available
Not Available
=> Fix data race in testutil

raftstore/proxy.go, raftstore/router.go
Fixes #624 
Not Available
Not Available
Not Available
=> Update route by not leader error

config/config.go
Fixes #
Not Available
Not Available
Not Available
=> add toml and json ignore tags to some config.Config fields

raftstore/replica_event_loop.go, raftstore/store_timer_task.go
Fixes #629 
Not Available
Not Available
Not Available
=> Keep data on state check

raftstore/replica_destroy.go, raftstore/replica_state_machine.go, raftstore/replica_state_machine_test.go
Fixes #631 
Not Available
Not Available
Not Available
=> Use appliedIndex+1 as tombstone metadata index

raftstore/store_shards_pool.go
Fixes #634 
Not Available
Not Available
Not Available
=> reset shard pool  stopper after stop

raftstore/proposal_batch.go, raftstore/read_index_queue.go, raftstore/read_index_queue_test.go, raftstore/replica.go, raftstore/replica_event_loop.go, raftstore/replica_event_proposal.go, raftstore/replica_event_raft_ready.go
Fixes #633 
Not Available
Not Available
Not Available
=> Fix read index not work after leader changed

raftstore/testutil.go
Fixes #637 
Not Available
Not Available
Not Available
=> Remove test data after test

components/prophet/election/election_leadship.go, components/prophet/election/election_test.go, components/prophet/member/member.go, components/prophet/prophet_leader.go, components/prophet/storage/kv_etcd_test.go, components/prophet/storage/storage_test.go
Fixes #639 
Not Available
Not Available
Not Available
=> Fix goroutine leak

raftstore/worker_pool_test.go
Fixes #
Not Available
Not Available
Not Available
=> Minor fix for a worker pool test

Makefile, util/leaktest/leak.go
Fixes #
Not Available
Not Available
Not Available
=> Enabled race detection and goroutine leak checks by default

.github/workflows/nightly.yml
Fixes #
Not Available
Not Available
Not Available
=> Added a nightly github action to run all tests

Makefile
Fixes #
Not Available
Not Available
Not Available
=> Modify the timeout of the test

config/config.go, raftstore/store.go, raftstore/testutil.go
Fixes #645 
Not Available
Not Available
Not Available
=> Make raft event worker count configurable

raftstore/worker_pool_test.go
Fixes #
Not Available
Not Available
Not Available
=> Added some logging for tests

components/prophet/client.go, components/prophet/cluster/cluster.go, components/prophet/cluster/cluster_worker.go, components/prophet/election/election_leadship.go, components/prophet/prophet.go, components/prophet/prophet_watcher.go
Fixes #650 
Not Available
Not Available
Not Available
=> Fix can not stop prophet

raftstore/proxy.go
Fixes #653 
Not Available
Not Available
Not Available
=> wrap ErrTimeout in retryDispatch

components/prophet/join/join.go
Fixes #
Not Available
Not Available
Not Available
=> Add more log for start embed etcd

raftstore/integration_schdule_test.go, raftstore/testutil.go
Fixes #659 
Not Available
Not Available
Not Available
=> Add fixed storage stats reader in tests

components/prophet/prophet_transport.go, raftstore/proxy_rpc.go
Fixes #
Not Available
Not Available
Not Available
=> fix defaultProphet and shardsproxy logger

components/prophet/join/join.go, components/prophet/prophet.go
Fixes #
Not Available
Not Available
Not Available
=> set etcd client logger

raftstore/worker_pool.go, raftstore/worker_pool_test.go
Fixes #
Not Available
Not Available
Not Available
=> Minor fix for testWorkerPoolConcurrentJobs

raftstore/store_bootstrap.go
Fixes #
Not Available
Not Available
Not Available
=> retry PutContainer in mustPutStore

components/prophet/join/join.go, raftstore/integration_basic_test.go, raftstore/testutil.go
Fixes #669 
Not Available
Not Available
Not Available
=> Support create prophet cluster use InitialCluster

raftstore/prophet_adapter.go
Fixes #671 
Not Available
Not Available
Not Available
=> Fix available space is calculated incorrectly

config/config.go
Fixes #
Not Available
Not Available
Not Available
=> add json and toml tag to CustomizeConfig.CustomWrapNewTransport

components/prophet/join/join.go
Fixes #
Not Available
Not Available
Not Available
=> Fix bootstrap with InitialCluster

components/prophet/schedulers/base_scheduler.go
Fixes #676 
Not Available
Not Available
Not Available
=> Remove unreachable code

components/prophet/config/config.go, components/prophet/config/config_job.go, components/prophet/config/default.go
Fixes #426 
Not Available
Not Available
Not Available
=> Fix copy lock

components/prophet/cluster/cluster_worker.go, components/prophet/pb/metapb/metapb.pb.go, components/prophet/pb/rpcpb/rpcpb.pb.go, pb/errorpb/error_ext.go, pb/errorpb/errorpb.pb.go, pb/errorpb/errorpb.proto, pb/meta/meta.pb.go, pb/rpc/rpc.pb.go, raftstore/batch.go, raftstore/errors.go, raftstore/integration_split_test.go, raftstore/proxy.go, raftstore/replica_destroy_task.go, raftstore/store.go, raftstore/store_timer_task.go, raftstore/testutil.go
Fixes #685 
Not Available
Not Available
Not Available
=> Fix write and read on unavailable shard

raftstore/replica_event_loop.go
Fixes #
Not Available
Not Available
Not Available
=> Fixed a log field name

Makefile, components/prophet/client_test.go, components/prophet/config/config.go, components/prophet/config/default.go, components/prophet/prophet_custom_test.go, components/prophet/prophet_handler.go, components/prophet/prophet_job_test.go, components/prophet/prophet_test.go
Fixes:
- race condition
- improve callback for test prophet
Not Available
Not Available
Not Available
=> Make unit test of components/prophet runnable;

raftstore/replica_destroy_task.go, raftstore/replica_event_loop.go
Fixes #
Not Available
Not Available
Not Available
=> merge main

storage/executor/executor_scanner.go, storage/executor/executor_scanner_test.go, storage/kv/keys.go, storage/kv/keys_test.go, storage/kv/kv_base_storage.go, storage/kv/pebble/storage.go, storage/storage_kv.go
Fixes #694 
Not Available
Not Available
Not Available
=> Add KV based storage scanner support

raftstore/testutil.go
Fixes #687 
Not Available
Not Available
Not Available
=> Fix set log level in test framework

components/prophet/cluster/cluster_test.go, components/prophet/cluster/cluster_worker.go, components/prophet/cluster/coordinator_test.go, components/prophet/core/resource.go, components/prophet/election/election_test.go
Fixes #
Not Available
Not Available
Not Available
=> fix test errors & data race

components/prophet/cluster/cluster.go, components/prophet/cluster/cluster_worker.go, components/prophet/id/id.go, components/prophet/id/id_mem.go, components/prophet/id/id_test.go, components/prophet/mock/mockcluster/mockcluster.go, components/prophet/prophet.go, components/prophet/prophet_handler.go, components/prophet/storage/kv.go, components/prophet/storage/kv_etcd.go, components/prophet/storage/kv_etcd_test.go, components/prophet/storage/kv_mem.go, components/prophet/storage/storage.go, components/prophet/storage/storage_test.go
Fixes #
Not Available
Not Available
Not Available
=> Rewrite id generator of prophet;

components/prophet/client.go, components/prophet/client_test.go, components/prophet/cluster/cluster.go, components/prophet/cluster/cluster_worker_test.go, components/prophet/core/shard_option.go, components/prophet/core/shard_tree.go, components/prophet/core/store.go, components/prophet/core/store_option.go, components/prophet/core/store_stats.go, components/prophet/event/event.go, components/prophet/event_notifier.go, components/prophet/event_watcher.go, components/prophet/mock/mockclient/client.go, components/prophet/prophet.go, pb/metapb/meta_ext.go, raftstore/router.go, raftstore/router_test.go, raftstore/store.go
Fixes #
Not Available
Not Available
Not Available
=> refactor event related code & fix typos in comments

client/client.go, raftstore/router.go, raftstore/router_test.go
Fixes #717 
Not Available
Not Available
Not Available
=> Support custom routing

components/prophet/client_test.go, components/prophet/storage/storage.go, components/prophet/storage/storage_test.go
Fixes #
Not Available
Not Available
Not Available
=> Add CustomStorage

components/prophet/client_test.go, components/prophet/prophet_job_test.go, components/prophet/prophet_test.go
https://github.com/matrixorigin/matrixcube/issues/719
Fixes #
Not Available
Not Available
Not Available
=> FIX issue 719;

raftstore/replica_apply_result.go, raftstore/replica_apply_result_test.go
Fixes #723 
Not Available
Not Available
Not Available
=> Fix approximateSize is incorrectly calculated

raftstore/router.go
Fixes #
Not Available
Not Available
Not Available
=> Update deprecated doc

components/prophet/storage/kv_etcd_test.go, components/prophet/storage/storage_test.go
Fixes  https://github.com/matrixorigin/matrixcube/issues/728
Not Available
Not Available
Not Available
=> Fix issue 728;

raftstore/router.go
Fixes #
Not Available
Not Available
Not Available
=> Fix dead lock

components/prophet/id/id.go, components/prophet/id/id_mem.go, components/prophet/id/id_test.go, components/prophet/join/join.go, components/prophet/member/member.go, components/prophet/prophet_job.go, components/prophet/storage/storage.go, components/prophet/util/errors.go, components/prophet/util/errors_test.go, raftstore/integration_create_shard_test.go, raftstore/store_shards_pool.go, raftstore/store_shards_pool_test.go
Fixes #
1. Respect the original license;
2. Update error handling for long running jobs;
3. Update method signature of `type interface JobStorage` for precise;
4. Fix some subtle nuance logic;
Not Available
Not Available
=> Update long running job related logic;

raftstore/store.go
Fixes #733 
Not Available
Not Available
Not Available
=> Handle shard closed error

util/btree_shard.go, util/btree_shard_test.go
Fixes #735 
Not Available
Not Available
Not Available
=> Fix AscendRange not work

storage/storage_data.go
Fixes #737 
Not Available
Not Available
Not Available
=> Deprecated bytebuf

Makefile
Fixes #
Not Available
Not Available
Not Available
=> Add txn test to makefile

components/prophet/config/config.go, config/config.go, raftstore/integration_create_shard_test.go, raftstore/integration_schdule_test.go
Fixes #
Not Available
Not Available
Not Available
=> Auto calculate shard group for prophet

util/hlc/hlc.go
Fixes #
Added NowUpperBound() to the Clock interface.
Not Available
Not Available
=> Added NowUpperBound() to the Clock interface

Makefile, pb/hlcpb/timestamp.go, storage/kv/kv_base_storage.go, storage/kv/pebble/storage.go, storage/storage_kv.go
Fixes #
More static check related fixes.
Not Available
Not Available
=> More static check related fixes

storage/executor/executor_scanner.go, storage/executor/executor_scanner_test.go
Fixes #754 
Not Available
Not Available
Not Available
=> Fix adjust scan end key logic

raftstore/store.go, storage/kv/kv_base_storage.go, storage/kv/kv_data_storage.go, storage/kv/storage_meta_test.go, storage/storage_data.go, txn/client/coordinator_test.go, txn/client/dispatcher_test.go, util/buf/buf.go, util/buf/buf_test.go, util/buf/mem_pool_test.go, util/stop/stopper_test.go, util/store.go, util/task/ring.go
Fixes #
Not Available
Not Available
Not Available
=> fix more static check

components/prophet/systime_mon.go
Fixes #767 
Not Available
Not Available
Not Available
=> fix time handling in StartMonitor

txn/kv/kv_command.go, txn/kv/kv_command_processor.go, txn/kv/kv_command_test.go
Fixes #
Not Available
Not Available
Not Available
=> Add txn kv batch get handle

storage/kv/kv_base_storage.go, storage/kv/kv_data_transactional_storage.go, storage/kv/kv_data_transactional_storage_test.go, storage/kv/pebble/storage.go, storage/kv/storage_meta_test.go, storage/storage_kv.go, txn/client/coordinator_test.go
Fixes #771 
Not Available
Not Available
Not Available
=> Fix kv get committed error

raftstore/store_extension_nontest.go
Fixes #
Not Available
Not Available
Not Available
=> expose LogDBGetter to make MO buildable without matrixone_test tag

raftstore/replica_state_machine_exec_test.go, storage/kv/kv_data_transactional_storage.go, storage/kv/kv_data_transactional_storage_test.go, storage/storage_data.go
Fixes #
Not Available
Not Available
Not Available
=> Unifying the return types of conflicting data

txn/manager/commit.go, txn/manager/handler.go, txn/manager/heartbeat.go, txn/manager/kv_test.go, txn/manager/latch.go, txn/manager/lock_table.go, txn/manager/manager.go, txn/manager/read.go, txn/manager/rollback.go, txn/manager/timestamp_cache.go, txn/manager/write.go
Fixes #
Not Available
Not Available
Not Available
=> tx manager codes (not finished)

config/config.go, raftstore/replica.go, raftstore/replica_event_loop.go, raftstore/store_test.go
Fixes #774 
Not Available
Not Available
Not Available
=> Add rate limit for request bytes

storage/stats/stats.go, storage/stats/stats_test.go
Fixes #
Not Available
Not Available
Not Available
=> Implement a method with copy semantics for stats.Stats;

raftstore/replica_apply_result.go, raftstore/replica_apply_result_test.go, raftstore/replica_create.go, raftstore/replica_state_machine_exec.go, raftstore/replica_state_machine_exec_test.go, raftstore/util.go
Fixes #
Not Available
Not Available
Not Available
=> Add lease for shard after split
